### PR TITLE
Bumps to alpha version of node-apn

### PR DESCRIPTION
**Pull request by flovilmart**
- Bumps engine
- Bumps CI
- Adds instructions for using custom adapter

### CODE REVIEW

**Comment by flovilmart** [comment]
Did you test the setup instructions? I already published the package, can you let us know how it goes? I’ll deploy it after new year

**Comment by funkenstrahlen** [comment]
@flovilmart The setup instructions are only required if I want to use a custom version of the push adapter, correct?

**Comment by flovilmart** [comment]
If you want to test this adapter at the 3.0.0-alpha1 version with your current parse server setup for example

**Comment by funkenstrahlen** [comment]
I checked the installation instructions. Works fine.

**Comment by funkenstrahlen** [comment]
I do run 3.0.0-alpha1 on my test backend now. Works fine so far. However the ping bug that should be solved with `apn 3.0.0-alpha1` never occurred on the test backend anyway because I have very few installations on this backend that can receive push notifications.

**Pull request closed without merging**
