### PR TITLE
API Compatibility

### PR DESCRIPTION
**Pull request by charles-ramos**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server-push-adapter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server-push-adapter/issues?q=is%3Aissue).

### Issue Description
Adding API Compatibility, so he user can now send both 'notification' and 'data' as objects for push notifications for Android.

Additionally, adding compatibility with nested objects, so, JSON is now accepted and the same behaviors from GCM are now replicable for FCM push notifications.

### TODOs before merging

- [ ] Add tests
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by mman** [comment]
@charles-ramos I honestly do not have any opinion on this PR. Is this PR bringing in some previous functionality that was working before and is now broken?

**Comment by jimnor0xF** [comment]
You can already use `notification` currently so it's unclear to me what this adds.

**Comment by charles-ramos** [comment]
Hey @mman and @jimnor0xF, the idea is to keep everything compatible with the current code (GCM) that uses "data" for sending push notifications for Android. Right now, in case I want to send push notifications to everyone (android and iOS), I must use both "data" and "notification". With the PR I raised, it will be possible to keep using "data" for both.

**Comment by mman** [comment]
@charles-ramos Are you using Parse Android SDK to receive the notifications? If you do could you post a snippet of your broadcast receiver that handles receiving the push?

**Comment by jimnor0xF** [comment]
@charles-ramos 
Are you sure you are using the Parse Android SDK for push notifications?

Back when we were using the Parse Android SDK we only used the `data` key. When we moved to using the native Firebase Cloud Messaging SDK then we started using the `notification` key. The `notification` key with that SDK is used for notifications that should pop up in the system tray. `data` is reserved for background (silent) notifications.

**Comment by charles-ramos** [comment]
Hi @mman and @jimnor0xF, I'm testing with the Javascript SDK.

```
Parse.Push.send({
  channels: [ "Giants", "Mets" ],
  data: {
    alert: "The Giants won against the Mets 2-3."
  }
})
.then(function() {
  // Push was successful
}, function(error) {
  // Handle error
});
```

With this PR, you can both send "notification" and "data" will work.  Without that, the "data" will not work for FCM.

Also, it will ensure that those who use the Parse Dashboard will be able to send push from there. It sends a notification as an "alert".

**Comment by mtrezza** [comment]
@charles-ramos Could you please resolve the conflicts?

**Comment by charles-ramos** [comment]
With the latest release (version 6.2.0), everything covered by this PR is already working, so it's no longer required to proceed with it. Thank you everyone.

**Comment by mtrezza** [comment]
Thanks for investigating

**Pull request closed without merging**
