### PR TITLE
Release v3.4.1

### PR DESCRIPTION
**Pull request by mtrezza**
- Security fixes (npm audit fix)

This will allow to close an open vulnerability with parse server.

### CODE REVIEW

**Comment by mtrezza** [comment]
@sadortun Could you do a review of this PR?

**Comment by sadortun** [comment]
@mtrezza sure! I'll be back Monday in the office Monday!

**Comment by mtrezza** [comment]
Great, we may merge this before that, but your review is always welcome!

**Review by sadortun — APPROVED** [review]

**Comment by mtrezza** [comment]
Thanks for your quick review!

**Pull request merged**
