### PR TITLE
Support headers in data field

### PR DESCRIPTION
**Pull request by dplewis**
https://docs.parseplatform.org/js/guide/#customizing-your-notifications

The docs says that the headers should be in the data field

### CODE REVIEW

**Comment by dplewis** [comment]
@acinader Should we support this or fast fail and update the docs?

**Comment by acinader** [comment]
i'm not sure what you're referring to in the docs.  is there an issue associated with this.  just not enough info for me to understand the issue.

**Comment by acinader** [comment]
Ok, now I see that this is for https://github.com/parse-community/parse-server/issues/6106

If I've got it right, I think we should fast fail and update the docs.

**Comment by dplewis** [comment]
@acinader @davimacedo I went ahead and allowed for both.

```
Parse.Push.send({
  channels: [ "Mets" ],
  push_type: ... // if used with have precedence over data field
  data: {
    alert: "The Mets scored! The game is now tied 1-1.",
    badge: "Increment",
    sound: "cheering.caf",
    title: "Mets Score!",
    push_type: ... // most users are familiar with the data field. changing it is a breaking change
  }
})
```

**Pull request merged**
