### PR TITLE
feat: Send Android push notifications to Firebase Cloud Messaging API (HTTP v1) by setting the push adapter option `firebaseServiceAccount`

### PR DESCRIPTION
**Pull request by jimnor0xF**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server-push-adapter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server-push-adapter/issues/219).

### Issue Description

Closes https://github.com/parse-community/parse-server-push-adapter/issues/219.

Adds FCM support to the parse-server-push-adapter.

### Approach

- Mostly re-uses the structure from GCM.js.
- Currently makes all deviceTypes use FCM. Not sure if this is what we want.
- Tested on both iOS and Android (flutter). 
- Requires the user to specify the exact payload they want. 

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
Payload example:
```javascript
  await Parse.Push.send(
    {
      where: query,
      notification: {
        title: title,
        body: body
      },
      data: {
        type: type
      },
      android: {
        priority: 'high'
      },
      apns: {
        headers: {
          'apns-priority': '5'
        },
        payload: {
          aps: {
            contentAvailable: true
          }
        }
      }
    },
    { useMasterKey: true }
  )

```

### TODOs before merging

- [ ] Add tests
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by jimnor0xF** [comment]
Correct, and I agree with all points listed above. Mostly wanted to get something working quick for myself to begin with ;)
I'll go ahead with the approach you suggested.

**Comment by mtrezza** [comment]
Great, and thanks for taking this on, this is really a key issue for many Parse Server deployments.

**Comment by jimnor0xF** [comment]
@mtrezza Addressed some of the points you mentioned.
i.e. maintain backwards compatability with the old GCM payload + make it possible to use the "raw" payload if wanted.

**Review by mtrezza — CHANGES_REQUESTED** [review]

**Comment by mtrezza** [comment]
@jimnor0xF Would you be so king and rebase this PR to resolve the conflicts? I've done some upgrading in other PRs.

**Comment by jimnor0xF** [comment]
> @jimnor0xF Would you be so king and rebase this PR to resolve the conflicts? I've done some upgrading in other PRs.

Rebased.

**Comment by mtrezza** [comment]
The package-lock has a suspiciously large change, even though only 1 dep has been added; could you please use the file from alpha and just run `npm i -ED firebase-admin@11.10.1` ?

**Comment by mtrezza** [comment]
@jimnor0xF Apologies, I wrote `-ED`, but this shouldn't be a dev dependency, right?

**Comment by mtrezza** [comment]
Thanks, running CI...

**Comment by paulrolfe** [comment]
Hey, just wanted to say thank you for this PR @jimnor0xF, I've put it into use in my project to send pushes using FCM and it's working great. Hope it gets merged into master soon.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server-push-adapter/releases/tag/5.1.0)

**Comment by astroblemeal** [comment]
Hello,

I'm experiencing issues with integrating Firebase Cloud Messaging using a service account on Heroku with `parse-server@7.1.0-alpha.6`. While the server functions correctly with the older GCM API, transitioning to FCM with service account credentials leads to a generic Heroku error without detailed diagnostics. Here are the steps I've followed:

**Base Installation:** parse-server@7.1.0-alpha.6 works with the legacy GCM API.

**Issue with FCM Service Account:** Problems begin when configuring the firebaseServiceAccount for FCM.

**Configuration Details:**

I exported the service account JSON file from the Google Cloud Console.

Set up the service account credentials in the server configuration as follows:

```
android: {
  firebaseServiceAccount: {
    type: "service_account",
    project_id: process.env.PUSH_ANDROID_PROJECT_ID,
    private_key_id: process.env.PUSH_ANDROID_PRIVATE_KEY_ID,
    private_key: process.env.PUSH_ANDROID_PRIVATE_KEY,
    client_email: process.env.PUSH_ANDROID_CLIENT_EMAIL,
    client_id: process.env.PUSH_ANDROID_CLIENT_ID,
    auth_uri: "https://accounts.google.com/o/oauth2/auth",
    token_uri: "https://oauth2.googleapis.com/token",
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
    client_x509_cert_url: process.env.PUSH_ANDROID_CERT_URL,
    universe_domain: "googleapis.com",
  }
}
```

I also tried using JSON.stringify on the object.

**Alternative Attempt:** I've also tried etting the firebaseServiceAccount as a path to the JSON file as suggested in `spec/ParsePushAdapter.spec.js`:

```
android: {
  firebaseServiceAccount: path.join(__dirname, 'foo', 'bar.json')
}
```

Both methods result in a generic Heroku error, and I'm unable to find relevant documentation on setting up the new FCM authentication method using a service account. Could you provide any insights or guidance on what might be causing these issues or how to resolve them?

**Comment by mtrezza** [comment]
There is a [fix](https://github.com/parse-community/parse-server-push-adapter/pull/238) we'll merge. If you then still encounter any issues please open a new GitHub issue.

**Pull request merged**
