### PR TITLE
3.0.4

### PR DESCRIPTION
**Pull request by davimacedo**

### CODE REVIEW

**Comment by davimacedo** [comment]
@TomWFox just done. Can you please take a look again?

**Comment by funkenstrahlen** [comment]
Awesome! Thanks for the new release!

**Comment by funkenstrahlen** [comment]
Are you able to push the new release to the npm package directory? Currently it does not know about all of the last releases: https://www.npmjs.com/package/@parse/push-adapter

**Comment by davimacedo** [comment]
Yes.. that's what I am trying to do for a while. Travis is supposed to publish it but it is failing. I am trying to figure it out.

**Comment by davimacedo** [comment]
@funkenstrahlen finally we have a new version released in npm. Parse Server should have it automatically updated in the next few hours as well.

**Pull request merged**
