### PR TITLE
Properly Handle Certificate Expired Error

### PR DESCRIPTION
**Pull request by dplewis**
I run into this issue about twice a year where my server crashes with 500 error. It's stuck this way until a new cert is renewed. 

If there is a Certificate Expired error on startup skip that push configuration.

There are more errors that could occur from the node-apn module but they rarely occur.

Let me know if there is a better way to do this.

### CODE REVIEW

**Comment by flovilmart** [comment]
I’m pretty much against this change as it will silently fail after and users won’t know that their certificate is expired. The best technique is to keep a sticky note as for when to rotate your certificates. 

If you have SSL on, you’ll have the same issue, if you forget when to rotate them, no one will be able to access your website/API. 

So for me, crashing is the right thing.

**Comment by dplewis** [comment]
@flovilmart I agree, Is there some way we can add an environment variable to make it optional?

**Comment by flovilmart** [comment]
It’s a lot of trouble for not a lot I believe. I mean, if there was a way to check the expiration and warn big time that the certificate was about to expire, that would be nice :) better than silently ignoring the cert invalidity.

The exception makes sense for me, it’s not recoverable, and the developer need to act rapidely.

**Comment by dplewis** [comment]
@flovilmart That would be great since I don't get emails from Apple for these kind of things. I think we can get the validity of the certs. I'll dig around some more.

**Comment by dplewis** [comment]
@flovilmart I opened a PR. https://github.com/node-apn/node-apn/pull/629 Let's see where this goes...

**Comment by dplewis** [comment]
Closing as properly handled

**Pull request closed without merging**
